#!/usr/bin/env bash

display_name="DELL U2723QE"

connected_to_workstation() {
  system_profiler SPDisplaysDataType | grep "${display_name}" >/dev/null
}

case "${1}" in
  displaywakeup|plug|wakeup)
    sleep 3
    if connected_to_workstation; then
      ~/bin/computer_speakers on
    fi
  ;;

  displaysleep|sleep)
    if connected_to_workstation; then
      ~/bin/computer_speakers off
    fi
  ;;

  *)
    echo "unknown command, or command not specified"
  ;;
esac
